const en_US = {
  SITE_TITLE: `NTX Social Mobility Hub`,
  LOADING_DATA: `Loading map data`,
  TEA_ID: `TEA identification number`,
  TERM_SCHOOL: `school`,
  BUTTON_VIEW_FEEDER: `Toggle feeder view`,
  BUTTON_VIEW_MAP: `Toggle map view`,
  BUTTON_CLOSE_PANEL: `Close slideout panel`,
  BUTTON_MENU: `Menu`,
  BUTTON_SEARCH: `Select to search`,
  INPUT_SEARCH: `Search for an address or location...`,
  INPUT_PLACEHOLDER_SEARCH: `Search... `,
  LINK_OPEN_FILTER_PANEL: `(change)`,
  BUTTON_TOGGLE_PANEL_FILTERS: `Toggle metrics/filters panel`,
  BUTTON_TOGGLE_PANEL_LAYERS: `Toggle layers panel`,
  BUTTON_TOGGLE_PANEL_WEIGHT: `Toggle weights panel`,
  BUTTON_TOGGLE_PANEL_INFO: `Toggle info panel`,
  CONTROL_PANEL_INFO: `HELP`,
  CONTROL_PANEL_METRICS: `METRICS`,
  CONTROL_PANEL_LAYERS: `LAYERS`,
  CONTROL_PANEL_FEATURES: `FEATURES`,
  CONTROL_PANEL_SHARE: `SHARE`,
  CONTROL_PANEL_SHARE_TC: `Share`,
  CONTROL_PANEL_VIEW: `VIEW`,
  BUTTON_TOUR: `Tour the Explorer`,
  BUTTON_SHARE_TWITTER: `Share on Twitter`,
  DIALOG_SHARE_TWITTER: `All Dallas neighborhoods should have what they need to thrive.`,
  BUTTON_SHARE_FACEBOOK: `Share on Facebook`,
  BUTTON_SHARE_EMAIL: `Share via email`,
  BUTTON_SHARE_LINK: `Get a custom link`,
  BUTTON_SHARE_UNIFIED: `Share`,
  DIALOG_SHARE_EMAIL_SUBJECT: `CPAL Resource Explorer`,
  DIALOG_SHARE_EMAIL_BODY: `All Dallas neighborhoods should have what they need to thrive. Use the CPAL Resource Explorer to see how schools benefit from local resources: `,
  MODAL_SHARE_LINK_HEAD: `Share a Link`,
  MODAL_SHARE_LINK_INSTR: `Copy the link below to share the current view of the Explorer.`,
  MODAL_SHARE_LINK_INPUT: `Current View URL`,
  BTN_CLOSE: `Close`,
  MAP_FILTERS_SELECT_LAYER: `Select a layer`,
  MAP_FILTERS_SELECT_INFO: `Scroll and select among the indicators listed
  below to apply them to the shapes in the map.`,
  MAP_FILTERS_SELECT_NONE: `No indicators are available for this georaphical
  layer.`,
  UI_MAP_FILTERS_INDICATORS: `Indicators`,
  UI_MAP_BUTTON_RESET_FILTER: `Reset active filter`,
  UI_MAP_FILTER_INSTRUCTIONS: `<p>Click the scale(s) below to activate metrics on the map. The brackets within each scale can be clicked on and off to filter the schools on the map. Clear filters by pressing the "reset" {icon} button above.</p>`,
  UI_MAP_FILTER_INSTRUCTIONS_UNTD: `<p>Different metrics are available for different geographic entities. Use the control below to select a different geographic entity.`,
  SELECT_VIEW: `Select a view`,
  SELECT_ITEM_MAP: `Map view`,
  SELECT_ITEM_FEEDER: `Feeder view`,
  UI_MAP_SR:
    'Map of Dallas, with colors showing {metric} for {quintiles}.',
  UI_MAP_RESET: `Reset map`,
  UI_MAP_CAPTURE: `Screenshot map`,
  UI_MAP_CITY: `Dallas`,
  UI_MAP_LEGEND_TITLE: `Selected metric:`,
  UI_MAP_TOGGLE_LAYERS: `TOGGLE LAYERS`,
  UI_MAP_LEGEND_SCHOOL_DOT: `School`,
  UI_MAP_LEGEND_SCHOOL_ZONE: `School zone (2 mile radius)`,
  UI_MAP_LEGEND_AVG: `About average`,
  UI_MAP_LEGEND_MORE: `Well above average`,
  UI_MAP_LEGEND_FEWER: `Well below average`,
  UI_MAP_LAYERS_ZIPS: `zip codes`,
  UI_MAP_FEATURE_ZIP: `zip code`,
  UI_MAP_LAYERS_COUNTIES: `counties`,
  UI_MAP_LAYERS_TRACTS: `census tracts`,
  UI_MAP_FEATURE_TRACT: `census tract`,
  UI_MAP_LAYERS_PLACES: `places`,
  UI_MAP_FEATURE_PLACE: `place`,
  UI_MAP_LAYER_0_TITLE: `Geographic Layers`,
  UI_MAP_LAYER_0_DESC: `<p>Toggle these layers on and off to learn more about the region.</p>`,
  UI_MAP_LAYER_1_TITLE: `Point Features`,
  UI_MAP_LAYER_1_DESC: `<p>Toggle these point features on and off to see individual neighborhood assets.</p>`,
  UI_MAP_LAYERS_BANKS: `Banks`,
  UI_MAP_LAYERS_COMMCS: `Community Centers`,
  UI_MAP_LAYERS_CREDITUS: `Credit Unions`,
  UI_MAP_LAYERS_PLAYGRS: `Playgrounds`,
  UI_MAP_LAYERS_SMARKETS: `Supermarkets`,
  POPUP_CLICK_TO_FEEDBACK: `Click to add feedback about this feature.`,
  TERM_INDEX_AVERAGE: `Index Average`,
  TERM_PLURAL: `{term}s`,
  UI_MAP_PANEL_HEADING: `Metric selection & filtering`,
  UI_MAP_PANEL_SELECT: `Select metric category:`,
  UI_MAP_PANEL_SELECT_QUINTILE: `Select quintile`,
  UI_MAP_PANEL_QUINTILE_0: `First quintile`,
  UI_MAP_PANEL_QUINTILE_1: `Second quintile`,
  UI_MAP_PANEL_QUINTILE_2: `Third quintile`,
  UI_MAP_PANEL_QUINTILE_3: `Fourth quintile`,
  UI_MAP_PANEL_QUINTILE_4: `Fifth quintile`,
  UI_MAP_PANEL_QUINTILE_ENABLE: `Enable {quintile} quintile`,
  UI_MAP_PANEL_QUINTILE_DISABLE: `Disable {quintile} quintile`,
  UI_MAP_PANEL_METRIC_ENABLE: `Enable metric {metric}`,
  UI_MAP_PANEL_METRIC_DISABLE: `Disable metric {metric}`,
  FIRST: `first`,
  SECOND: `second`,
  THIRD: `third`,
  FOURTH: `fourth`,
  FIFTH: `fifth`,
  ALL_FIVE: `all five`,
  QUINTILE: `quintile`,
  QUINTILES: `quintiles`,
  NO: `no`,
  AND: `and`,
  UI_CONTROL_PANEL_VIEW: `View`,
  UI_CONTROL_PANEL_VIEW: `Filter`,
  UI_CONTROL_PANEL_VIEW: `Share`,
  UI_MAP_METRIC_DEM_TOTP: `Total population`,
  UI_MAP_METRIC_DEM_POPWH: `White, Non-Hispanic population`,
  UI_MAP_METRIC_DEM_POPBL: `Black, Non-Hispanic population`,
  UI_MAP_METRIC_DEM_POPAS: `Asian, Non-Hispanic population`,
  UI_MAP_METRIC_DEM_POPHI: `Hispanic population`,
  UI_MAP_METRIC_DEM_PERPOC: `Persons of color`,
  UI_MAP_METRIC_DEM_POPM: `Male population`,
  UI_MAP_METRIC_DEM_POPF: `Female population`,
  UI_MAP_METRIC_DEM_THH: `Total households`,
  UI_MAP_METRIC_DEM_POPSE: `Senior population (65 and Over)`,
  UI_MAP_METRIC_DEM_POPCH: `Child population (Under 18)`,
  // Added 2020-08-26
  UI_MAP_METRIC_DEM_PERWH: `Percent of White, Non-Hispanic Population in Buffer`,
  UI_MAP_METRIC_DEM_PERAS: `Percent of Asian, Non-Hispanic Population in Buffer`,
  UI_MAP_METRIC_DEM_PERBL: `Percent of Black, Non-Hispanic Population in Buffer`,
  UI_MAP_METRIC_DEM_PERCH: `Percent of Child Population (Under 18) in Buffer`,
  UI_MAP_METRIC_DEM_PERF: `Percent of Female Population, All Ages in Buffer`,
  UI_MAP_METRIC_DEM_PERHI: `Percent of Hispanic Population, All Races in Buffer`,
  UI_MAP_METRIC_DEM_PERM: `Percent of Male Population, All Ages in Buffer`,
  UI_MAP_METRIC_DEM_PERSE: `Percent of Senior Population (65 and Over) in Buffer`,
  // End added 2020-08-26
  UI_PANEL_INFO_MAP: `<h5>Exploring in the map view</h5>

  <p>The map displays North Dallas geographic entities, each color-coded to show their score within the selected economic opportunity metric. The color scale has 5 blocks, each representing a quintile within the scale. The lighter the color, the higher the score.</p>

  <p>You can change the metric shown on the map by clicking the METRICS button and making selections. You can also use this feature to filter geographic entities on the map by quintile.</p>

  <p>The map also contains point features for a wide variety of neighborhood assets. You can enable and disable these point features by clicking the FEATURES button.</p>

  <p>To add feedback about a geographic entity or point feature, click that location on the map. A panel will open with a pre-populated form.</p>

  <p>You can also grab a snapshot of your screen using the camera button, and share a custom link to your current Explorer view via the SHARE buttons.</p>

  <p>Questions? Visit our <a href="/faq" target="_blank">FAQ</a>.</p>`,
  UI_MAP_CLICK_SCHOOL_PROMPT: `Click on school to view full report.`,
  UI_MAP_SCHOOL_ACCESS_LINK: `Access full report.`,
  UI_MAP_FLY_TO_PROMPT: `Hover school for more information, or click
  school to see a detailed report.`,
  UI_MAP_FLY_TO_PROMPT_MOBILE: `Touch school for more information.`,
  UI_MAP_INTRO_MODAL_HEADER: `Community Resource Explorer`,
  UI_MAP_INTRO_MODAL_INTRO: `The map and charts in this tool allow users to learn about economic opportunity in north Texas. You can take several paths to get started.`,
  UI_MAP_INTRO_MODAL_TOUR: `Take a tour of the Explorer to learn about its features.`,
  UI_MAP_INTRO_MODAL_TOUR_BTN: `Take a tour`,
  UI_MAP_INTRO_MODAL_SEARCH: `Search for a location in your own neighborhood.`,
  UI_MAP_INTRO_MODAL_SEARCH_BTN: `Search`,
  UI_MAP_INTRO_MODAL_FAQ: `Read our FAQs to learn more about the project.`,
  UI_MAP_INTRO_MODAL_FAQ_BTN: `Go to FAQs`,
  UI_MAP_INTRO_MODAL_MAP: `Jump in and start exploring.`,
  UI_MAP_INTRO_MODAL_MAP_BTN: `Go straight to the map!`,
  UI_MAP_SCHOOL_MODAL_DETAILS_BTN: `View School Details`,
  UI_FEEDER_SCROLL_PROMPT: `Scroll for more`,
  UI_FEEDER_DIST_LEGEND_HIGHLIGHT: `Highlighted school`,
  UI_FEEDER_DIST_LEGEND_FEEDER: `Schools in the selected feeder pattern`,
  UI_MAP_SEE_LEGEND: `Show legend`,
  MAP_UI_POWERED_BY: `Powered by the&nbsp;<a href="https://childpovertyactionlab.org/" target="_blank" rel="noreferrer">Child Poverty Action Lab (CPAL)</a>`,
  FEEDER_UI_CLICK_FOR_ADDL: `Click for additional information`,
  TOUR_UI_ACTIONS_BACK: `Back`,
  TOUR_UI_ACTIONS_CLOSE: `Close`,
  TOUR_UI_ACTIONS_LAST: `Last`,
  TOUR_UI_ACTIONS_NEXT: `Next`,
  TOUR_UI_ACTIONS_SKIP: `Skip`,
  TOUR_DESK_STEP_0: `Use these buttons to select the view. There are two options: a Map view...`,
  TOUR_DESK_STEP_1: `... and a School Feeder Pattern view.`,
  TOUR_DESK_STEP_0_1: `Use this control to select the view. There are two view options: a Map view and a School Feeder Pattern view.`,
  TOUR_DESK_STEP_2: `In the map view, geographic entities are displayed and colored according to where they fall in the currently selected metric. On hover, a tooltip provides more information about regions as well as point features on the map.`,
  TOUR_MOBILE_STEP_2: `In the map view, geographic entities are displayed and colored according to where they fall in the currently selected metric.`,
  TOUR_DESK_STEP_3: `Use these controls to zoom in and out, take a screenshot of the map, and reset the map.`,
  TOUR_DESK_STEP_4: `The map legend shows which intervals of the currently selected metric are toggled on or off.`,
  TOUR_DESK_STEP_5: `Use the metrics panel to customize which geographic entities are displayed on the map along with the active metric.`,
  TOUR_DESK_STEP_6: `Use the dropdown to switch between different types of regions like zip codes, census tracts, and so on.`,
  TOUR_MOBILE_STEP_7: `Tap a metric to toggle certain intervals on or off.`,
  TOUR_DESK_STEP_7: `Click a metric to toggle certain intervals on or off.`,
  TOUR_DESK_STEP_8: `Click checkboxes within the features panel to toggle different types of features on or off.`,
  TOUR_MOBILE_STEP_8: `Tap checkboxes within the features panel to toggle different types of features on or off.`,
  TOUR_DESK_STEP_9: `Search for a location using the search bar. When selecting a location, the map will zoom and pan to center this location in the viewport. `,
  TOUR_DESK_STEP_10: `Use the share menu to distribute the explorer on social media, via email, or embed.`,
  TOUR_DESK_STEP_11: `The info panel contains additional information about the interface and its use.`,
  TOUR_DESK_STEP_12: `If necessary, use the "Tour" button to display this information again.`,
  TOUR_MOBILE_STEP_12: `If necessary, use the "Tour" button in the info panel to display this information again.`,
  BUTTON_RESET_POINTS: `Reset all point features`,
  TOOLTIP_PLACE_TRACT: `Census tract {label}`,
  TOOLTIP_PLACE_ZIP: `Zip code {label}`,
  TOOLTIP_PLACE_COUNTY: `{label} County`,
  FEEDBACK_HEADING: `We're happy to have your feedback!`,
  FEEDBACK_INSTR_WITHFEATURE: `<p>Use the form below to submit feedback about your selected point or geographic feature. The address field has been pre-populated with the selected location.</p>`,
  FEEDBACK_INSTR: `<p>Use the form below to submit feedback about the map. If there's a location in your neighborhood that is no longer there, something new, or inaccurate information, please let us know!</p><p>The "Use my current location" button will tie your feedback to your current location. You can also search for an addres or point of interest.</p>`,
  FEEDBACK_USE_CURRENT_LOC: `Use my current location`,
  FEEDBACK_SUBMIT: `Submit`,
  CONTACT_EMAIL: `analytics@childpovertyactionlab.org`,
  CONTACT_MAILTO: `maito:{email}`,
  FEEDBACK_SUBMIT_FAILURE: `Sorry, something went wrong with the form
  submission. If you like you can still <a href="mailto:{email}>contact us by email</a>.`,
  FEEDBACK_SUCCESS: `Messsage received! Thanks for contacting us.`,
  FEEDBACK_SUBMITTING: `Submitting...`,
  FEEDBACK_CANCEL: `Cancel`,
  OR: `or`,
}

export default en_US
