const en_US = {
  SITE_TITLE: `UNTD Map`,
  LOADING_DATA: `Loading map data`,
  TEA_ID: `TEA identification number`,
  TERM_SCHOOL: `school`,
  BUTTON_VIEW_FEEDER: `Toggle feeder view`,
  BUTTON_VIEW_MAP: `Toggle map view`,
  BUTTON_CLOSE_PANEL: `Close slideout panel`,
  BUTTON_MENU: `Menu`,
  BUTTON_SEARCH: `Select to search`,
  INPUT_SEARCH: `Search for a Dallas ISD school`,
  INPUT_PLACEHOLDER_SEARCH: `Search... `,
  LINK_OPEN_FILTER_PANEL: `(change)`,
  BUTTON_TOGGLE_PANEL_FILTERS: `Toggle metrics/filters panel`,
  BUTTON_TOGGLE_PANEL_LAYERS: `Toggle layers panel`,
  BUTTON_TOGGLE_PANEL_WEIGHT: `Toggle weights panel`,
  BUTTON_TOGGLE_PANEL_INFO: `Toggle info panel`,
  CONTROL_PANEL_INFO: `HELP`,
  CONTROL_PANEL_METRICS: `METRICS`,
  CONTROL_PANEL_LAYERS: `LAYERS`,
  CONTROL_PANEL_SHARE: `SHARE`,
  CONTROL_PANEL_SHARE_TC: `Share`,
  CONTROL_PANEL_VIEW: `VIEW`,
  BUTTON_TOUR: `Tour the Explorer`,
  BUTTON_SHARE_TWITTER: `Share on Twitter`,
  DIALOG_SHARE_TWITTER: `All Dallas neighborhoods should have what they need to thrive.`,
  BUTTON_SHARE_FACEBOOK: `Share on Facebook`,
  BUTTON_SHARE_EMAIL: `Share via email`,
  BUTTON_SHARE_LINK: `Get a custom link`,
  BUTTON_SHARE_UNIFIED: `Share`,
  DIALOG_SHARE_EMAIL_SUBJECT: `CPAL Resource Explorer`,
  DIALOG_SHARE_EMAIL_BODY: `All Dallas neighborhoods should have what they need to thrive. Use the CPAL Resource Explorer to see how schools benefit from local resources: `,
  MODAL_SHARE_LINK_HEAD: `Share a Link`,
  MODAL_SHARE_LINK_INSTR: `Copy the link below to share the current view of the Explorer.`,
  MODAL_SHARE_LINK_INPUT: `Current View URL`,
  BTN_CLOSE: `Close`,
  UI_MAP_FILTERS_INDICATORS: `Indicators`,
  UI_MAP_BUTTON_RESET_FILTER: `Reset active filter`,
  UI_MAP_FILTER_INSTRUCTIONS: `<p>Click the scale(s) below to activate metrics on the map. The brackets within each scale can be clicked on and off to filter the schools on the map. Clear filters by pressing the "reset" {icon} button above.</p>`,
  SELECT_VIEW: `Select a view`,
  SELECT_ITEM_MAP: `Map view`,
  SELECT_ITEM_FEEDER: `Feeder view`,
  UI_MAP_SR:
    'Map of Dallas, with colors showing {metric} for {quintiles}.',
  UI_MAP_RESET: `Reset map`,
  UI_MAP_CAPTURE: `Screenshot map`,
  UI_MAP_CITY: `Dallas`,
  UI_MAP_LEGEND_TITLE: `Selected index:`,
  UI_MAP_TOGGLE_LAYERS: `TOGGLE LAYERS`,
  UI_MAP_LEGEND_SCHOOL_DOT: `School`,
  UI_MAP_LEGEND_SCHOOL_ZONE: `School zone (2 mile radius)`,
  UI_MAP_LEGEND_AVG: `About average`,
  UI_MAP_LEGEND_MORE: `Well above average`,
  UI_MAP_LEGEND_FEWER: `Well below average`,
  UI_MAP_LAYERS_ZIPS: `Zip codes`,
  UI_MAP_LAYERS_COUNTIES: `Counties`,
  UI_MAP_LAYERS_TRACTS: `Census tracts`,
  UI_MAP_FEATURE_TRACT: `Census tract`,
  UI_MAP_LAYERS_PLACES: `Places`,
  UI_MAP_LAYER_0_TITLE: `Geographic Layers`,
  UI_MAP_LAYER_0_DESC: `<p>Toggle these layers on and off to learn more about the region.</p>`,
  UI_MAP_LAYER_1_TITLE: `Point Features`,
  UI_MAP_LAYER_1_DESC: `<p>Toggle these layers on and off to see individual neighborhood assets.</p>`,
  UI_MAP_LAYERS_BANKS: `Banks`,
  UI_MAP_LAYERS_COMMCS: `Community Centers`,
  UI_MAP_LAYERS_CREDITUS: `Credit Unions`,
  UI_MAP_LAYERS_PLAYGRS: `Playgrounds`,
  UI_MAP_LAYERS_SMARKETS: `Supermarkets`,

  UI_MAP_METRIC_ABBREV_CRI: `CRI`,
  UI_MAP_METRIC_TITLE_CRI: `Community Resource Index`,
  UI_MAP_METRIC_DESC_CRI: `<p>The Community Resource Index is an average of all Index categories (economics, education, family, health, and community). It presents an overall view of the resources available to each school’s surrounding community.</p>`,
  UI_MAP_METRIC_TITLE_ECON: `Economics`,
  UI_MAP_METRIC_DESC_ECON: `<p><span>Do residents have access to financial services and well-paying jobs?</span><br /><br />Communities with the highest scores on this index are more likely to have higher household incomes, more access to banks and credit unions, lower unemployment rates, and greater access to jobs of all types.</p>`,
  UI_MAP_METRIC_TITLE_EDU: `Education`,
  UI_MAP_METRIC_DESC_EDU: `<p><span>How accessible are ancillary educational services, like quality childcare and afterschool programs, in the community? Have residents completed college?</span><br /><br />Communities with the highest scores on this index have greater access to quality early childhood education, more afterschool program capacity, and a greater share of adults with college degrees.</p>`,
  UI_MAP_METRIC_TITLE_FAM: `Family`,
  UI_MAP_METRIC_DESC_FAM: `<p><span>Are families able to access childcare in the community?</span><br /><br />Communities with the highest scores on this index are more likely to have a greater share of two-parent households (of households with children) and more access to childcare providers.</p>`,
  UI_MAP_METRIC_TITLE_HEAL: `Health`,
  UI_MAP_METRIC_DESC_HEAL: `<p><span>Do residents have access to health insurance, medical services, and fresh fruits and vegetables? Are residents healthy?</span><br /><br />Communities with the highest scores on this index have more access to health clinics and pharmacies and have a greater share of residents with health insurance. Communities with high Health scores also have longer life expectancies and fewer health issues.</p>`,
  UI_MAP_METRIC_TITLE_COMM: `Community`,
  UI_MAP_METRIC_DESC_COMM: `<p><span>Does the community have public amenities? Is the community safe? Are families and businesses secure?</span><br /><br />Communities with the highest scores on this index have more public spaces for community members, fewer cost-burdened households, and fewer residential and business vacancies.</p>`,
  UI_MAP_METRIC_TITLE_ECON_INDEX: `Economics Index`,
  UI_MAP_METRIC_TITLE_EDU_INDEX: `Education Index`,
  UI_MAP_METRIC_TITLE_FAM_INDEX: `Family Index`,
  UI_MAP_METRIC_TITLE_HEAL_INDEX: `Health Index`,
  UI_MAP_METRIC_TITLE_COMM_INDEX: `Community Index`,
  UI_MAP_METRIC_TITLE_COMM_BBP: `Households with broadband access (%)`,
  UI_MAP_METRIC_COMM_BVP: `Overall business vacancies (%)`,
  UI_MAP_METRIC_COMM_CCTRCAP: `Community and recreation centers, per 10,000 residents`,
  UI_MAP_METRIC_COMM_INCARPCT: `Adults incarcerated (%)`,
  UI_MAP_METRIC_COMM_JUVCRIMECAP: `Juvenile-committed violent crime incidents, per 10,000 residents between ages 16-24`,
  UI_MAP_METRIC_COMM_LIBCAP: `Libraries, per 10,000 residents`,
  UI_MAP_METRIC_COMM_LTBVP: `Long-term business vacancies (24+ months) (%)`,
  UI_MAP_METRIC_COMM_LTRVP: `Long-term residential vacancies (24+ months) (%)`,
  UI_MAP_METRIC_COMM_OCB: `Owner-occupied households that are cost burdened`,
  UI_MAP_METRIC_COMM_OCBP: `Owner-occupied households that are cost-burdened (%)`,
  UI_MAP_METRIC_COMM_PARKCAP: `Park area (sq mi), per 10,000 residents`,
  UI_MAP_METRIC_COMM_RCB: `Renter occupied households that are cost burdened`,
  UI_MAP_METRIC_COMM_RCBP: `Renter-occupied households that are cost-burdened (%)`,
  UI_MAP_METRIC_COMM_RVP: `Overall residential vacancies (%)`,
  UI_MAP_METRIC_COMM_U18BBP: `Children under 18 with broadband access (%)`,
  UI_MAP_METRIC_COMM_EVRATE: `Number of evictions, per 10,000 residents`,
  UI_MAP_METRIC_ECON_CPR: `Child poverty rate (%)`,
  UI_MAP_METRIC_ECON_FINCAP: `Banks and credit unions, per 10,000 residents`,
  UI_MAP_METRIC_ECON_MEDINC: `Median household income`,
  UI_MAP_METRIC_ECON_PAYDAYCAP: `Payday lending and cash advance businesses, per 10,000 residents`,
  UI_MAP_METRIC_ECON_PCTLWJOBS: `Jobs earning less than $1,500 a month (%)`,
  UI_MAP_METRIC_ECON_PCTMWJOBS: `Jobs earning between $1,500 and $3,333 a month (%)`,
  UI_MAP_METRIC_ECON_PR: `Poverty rate`,
  UI_MAP_METRIC_ECON_PYR: `Youth (ages 16-24) unemployment rate (%)`,
  UI_MAP_METRIC_ECON_UR: `Unemployment rate`,
  UI_MAP_METRIC_EDU_OOSTKIDS: `Afterschool program seats, per 10,000 children under age 18`,
  UI_MAP_METRIC_EDU_PERBACH: `Residents with a bachelor's degree`,
  UI_MAP_METRIC_EDU_PEREARLYED: `Children ages 3-4 enrolled in school`,
  UI_MAP_METRIC_EDU_QECKIDS: `High-quality, early childcare seats, per 10,000 children between ages 3 and 4`,
  UI_MAP_METRIC_ECON_TOTJOBS: `Total jobs`,
  UI_MAP_METRIC_FAM_AFFCCKIDS: `Licensed, affordable childcare centers, per 10,000 children under age 5`,
  UI_MAP_METRIC_FAM_LCCKIDS: `Licensed childcare centers, per 10,000 children under age 5`,
  UI_MAP_METRIC_FAM_TPHH: `Two-parent households`,
  UI_MAP_METRIC_FAM_TPHHPCT: `Two-parent households (%)`,
  UI_MAP_METRIC_HEL_BPHIGH: `Adults with high blood pressure, per 10,000 residents`,
  UI_MAP_METRIC_HEL_CASTTHMA: `Adults with asthma, per 10,000 residents`,
  UI_MAP_METRIC_HEL_CHECKUP: `Number of routine doctor visits annually, per 10,000 residents`,
  UI_MAP_METRIC_HEL_FRUITSVEGGIES: `Average spending on fresh fruits and vegetables monthly`,
  UI_MAP_METRIC_HEL_LE: `Average life expectancy`,
  UI_MAP_METRIC_HEL_MHLTH: `Adults reporting poor mental health for 14 days or more, per 10,000 residents`,
  UI_MAP_METRIC_HEL_OBESITY: `Adult obesity, per 10,000 residents`,
  UI_MAP_METRIC_HEL_PERPRI: `Population with private health insurance (%)`,
  UI_MAP_METRIC_HEL_PERPUB: `Population with public health insurance (%)`,
  UI_MAP_METRIC_HEL_PHARMACAP: `Licensed pharmacies, per 10,000 residents`,
  UI_MAP_METRIC_HEL_PHLTH: `Adults with poor physical health, per 10,000 residents`,
  UI_MAP_METRIC_HEL_SLEEP: `Adults Sleeping less than 7 hours per Night, per 10,000 Residents`,
  UI_MAP_METRIC_HEL_STROKE: `Adults who have had a Stroke, per 10,000 Residents`,
  UI_MAP_METRIC_HEL_CLINCAP: `Number of clinics, per 10,000 residents`,
  UI_MAP_METRIC_HEL_GROCCAP: `Number of grocery stores, per 10,000 residents`,
  UI_MAP_METRIC_HEL_PRTOPU: `Not available`,
  UI_MAP_METRIC_HEL_PERINS: `Population with health insurance (%)`,
  UI_MAP_METRIC_HEL_PERUNIN: `Population without Health Insurance (%)`,
  UI_FEEDER_TITLE_FEEDER_CHART: `Dallas ISD School Feeder Patterns`,
  UI_PANEL_INFO_FEEDER_DESC: `<h3>About the Feeder Pattern View</h3><p>A feeder pattern is the sequence of schools a student attends as they advance from grade to grade, based on their residing address.</p><p>The first chart shows each feeder pattern’s average Community Resource Index on a scale from 0-100.</p><p>The second chart shows the distribution of campuses across the range of the Community Resource Index.</p>`,
  UI_FEEDER_TITLE_FEEDER_DESC: `<p>Hover and click within the charts to see more data about each feeder pattern and its schools. You can also use the search bar to find a school and highlight its feeder pattern and campus.</p>`,
  UI_FEEDER_TITLE_SCHOOLS_CHART: `Distribution of campuses across CRI`,
  UI_FEEDER_TOOLTIP_INDEX_DESC: `*Index scores measured 0 to 100`,
  UI_FEEDER_TOOLTIP_SUBINDEX_AVG: `Average {metric} index score:`,
  UI_FEEDER_FEEDER_CHART_DESC: `Bar chart indicating average CRI for each feeder in Dallas ISD.`,
  UI_FEEDER_SCHOOL_CHART_DESC: `Scatterplot chart indicating number of schools with a given CRI value. Schools are highlighted when their feeder is hovered in the feeder chart.`,
  UI_MAP_TOOLTIP_FEEDER: `{name} Schools`,
  TERM_INDEX_AVERAGE: `Index Average`,
  TERM_PLURAL: `{term}s`,
  UI_MAP_PANEL_HEADING: `Index selection & filtering`,
  UI_MAP_PANEL_SELECT: `Select index category:`,
  UI_MAP_PANEL_SELECT_QUINTILE: `Select quintile`,
  UI_MAP_PANEL_QUINTILE_0: `First quintile`,
  UI_MAP_PANEL_QUINTILE_1: `Second quintile`,
  UI_MAP_PANEL_QUINTILE_2: `Third quintile`,
  UI_MAP_PANEL_QUINTILE_3: `Fourth quintile`,
  UI_MAP_PANEL_QUINTILE_4: `Fifth quintile`,
  UI_MAP_PANEL_QUINTILE_ENABLE: `Enable {quintile} quintile`,
  UI_MAP_PANEL_QUINTILE_DISABLE: `Disable {quintile} quintile`,
  UI_MAP_PANEL_METRIC_ENABLE: `Enable metric {metric}`,
  UI_MAP_PANEL_METRIC_DISABLE: `Disable metric {metric}`,
  FIRST: `first`,
  SECOND: `second`,
  THIRD: `third`,
  FOURTH: `fourth`,
  FIFTH: `fifth`,
  ALL_FIVE: `all five`,
  QUINTILE: `quintile`,
  QUINTILES: `quintiles`,
  NO: `no`,
  AND: `and`,
  UI_CONTROL_PANEL_VIEW: `View`,
  UI_CONTROL_PANEL_VIEW: `Filter`,
  UI_CONTROL_PANEL_VIEW: `Share`,
  UI_MAP_METRIC_DEM_TOTP: `Total population`,
  UI_MAP_METRIC_DEM_POPWH: `White, Non-Hispanic population`,
  UI_MAP_METRIC_DEM_POPBL: `Black, Non-Hispanic population`,
  UI_MAP_METRIC_DEM_POPAS: `Asian, Non-Hispanic population`,
  UI_MAP_METRIC_DEM_POPHI: `Hispanic population`,
  UI_MAP_METRIC_DEM_PERPOC: `Persons of color`,
  UI_MAP_METRIC_DEM_POPM: `Male population`,
  UI_MAP_METRIC_DEM_POPF: `Female population`,
  UI_MAP_METRIC_DEM_THH: `Total households`,
  UI_MAP_METRIC_DEM_POPSE: `Senior population (65 and Over)`,
  UI_MAP_METRIC_DEM_POPCH: `Child population (Under 18)`,
  // Added 2020-08-26
  UI_MAP_METRIC_DEM_PERWH: `Percent of White, Non-Hispanic Population in Buffer`,
  UI_MAP_METRIC_DEM_PERAS: `Percent of Asian, Non-Hispanic Population in Buffer`,
  UI_MAP_METRIC_DEM_PERBL: `Percent of Black, Non-Hispanic Population in Buffer`,
  UI_MAP_METRIC_DEM_PERCH: `Percent of Child Population (Under 18) in Buffer`,
  UI_MAP_METRIC_DEM_PERF: `Percent of Female Population, All Ages in Buffer`,
  UI_MAP_METRIC_DEM_PERHI: `Percent of Hispanic Population, All Races in Buffer`,
  UI_MAP_METRIC_DEM_PERM: `Percent of Male Population, All Ages in Buffer`,
  UI_MAP_METRIC_DEM_PERSE: `Percent of Senior Population (65 and Over) in Buffer`,
  // End added 2020-08-26
  UI_PANEL_INFO_MAP: `<h5>Exploring in the map view</h5>

  <p>The map displays 189 Dallas ISD schools, each color-coded to show their score within the metrics that make up the Community Resource Index. The color scale has 5 blocks, each representing a quintile within the scale. The lighter the color, the higher the score.</p>

  <p>You can change the metric shown on the map by clicking the METRICS button and making selections. You can also use this feature to filter schools on the map by quintiles.</p>

  <p>To see the entire list of metrics for a school, click its dot on the map. A full report about this school will appear in a new tab in your browser.</p>

  <p>Use the “toggle map layers” feature to see historical redlining zones (<a href="/faq/#use-2" target="_blank">see FAQ for more</a>) and toggle district boundaries on and off.</p>

  <p>You can also grab a snapshot of your screen using the camera button, and share a custom link to your current Explorer view via the SHARE buttons.</p>

  <p>Questions? Visit our <a href="/faq" target="_blank">FAQ</a>.</p>`,
  UI_PANEL_INFO_FEEDER: `<h5>Exploring in the Feeder Pattern View</h5><p>A feeder pattern is the sequence of schools a student attends as they advance from grade to grade, based on where they live.</p><p>The first chart shows each feeder pattern’s average Community Resource Index on a scale from 0-100.</p><p>The second chart shows the distribution of campuses across the range of the Community Resource Index.</p> <p>Hover and click within the charts to see more data about each feeder pattern and its schools. You can also use the search bar to find a school and highlight its feeder pattern and campus.</p>`,
  UI_MAP_CLICK_SCHOOL_PROMPT: `Click on school to view full report.`,
  UI_MAP_SCHOOL_ACCESS_LINK: `Access full report.`,
  UI_MAP_FLY_TO_PROMPT: `Hover school for more information, or click
  school to see a detailed report.`,
  UI_MAP_FLY_TO_PROMPT_MOBILE: `Touch school for more information.`,
  UI_MAP_INTRO_MODAL_HEADER: `Community Resource Explorer`,
  UI_MAP_INTRO_MODAL_INTRO: `The map and charts in this tool allow users to learn about resource distribution in the Dallas Independent School District. You can take several paths to get started.`,
  UI_MAP_INTRO_MODAL_TOUR: `Take a tour of the Explorer to learn about its features.`,
  UI_MAP_INTRO_MODAL_TOUR_BTN: `Take a tour`,
  UI_MAP_INTRO_MODAL_SEARCH: `Search for a school to start in your own neighborhood.`,
  UI_MAP_INTRO_MODAL_SEARCH_BTN: `Search`,
  UI_MAP_INTRO_MODAL_FAQ: `Read our FAQs to learn more about the project.`,
  UI_MAP_INTRO_MODAL_FAQ_BTN: `Go to FAQs`,
  UI_MAP_INTRO_MODAL_MAP: `Jump in and start exploring.`,
  UI_MAP_INTRO_MODAL_MAP_BTN: `Go straight to the map!`,
  UI_MAP_SCHOOL_MODAL_DETAILS_BTN: `View School Details`,
  UI_FEEDER_SCROLL_PROMPT: `Scroll for more`,
  UI_FEEDER_DIST_LEGEND_HIGHLIGHT: `Highlighted school`,
  UI_FEEDER_DIST_LEGEND_FEEDER: `Schools in the selected feeder pattern`,
  UI_MAP_SEE_LEGEND: `Show legend`,
  MAP_UI_POWERED_BY: `Powered by&nbsp;<a href="https://google.com/" target="_blank" rel="noreferrer">Custom Attribution</a>`,
  FEEDER_UI_CLICK_FOR_ADDL: `Click for additional information`,
  TOUR_UI_ACTIONS_BACK: `Back`,
  TOUR_UI_ACTIONS_CLOSE: `Close`,
  TOUR_UI_ACTIONS_LAST: `Last`,
  TOUR_UI_ACTIONS_NEXT: `Next`,
  TOUR_UI_ACTIONS_SKIP: `Skip`,
  TOUR_DESK_STEP_0: `Use these buttons to select the view. There are two options: a Map view...`,
  TOUR_DESK_STEP_1: `... and a School Feeder Pattern view.`,
  TOUR_DESK_STEP_0_1: `Use this control to select the view. There are two view options: a Map view and a School Feeder Pattern view.`,
  TOUR_DESK_STEP_2: `In the Map view, schools are shown as colored dots. \n\nThe color of each dot represents how resource-rich the school community is relative to others in Dallas ISD.`,
  TOUR_DESK_STEP_3: `Use the Metrics panel to choose from different indices and indicators to display on the map.`,
  TOUR_DESK_STEP_4: `The menu at the top of the Metrics panel allows you to select different categories of indices and indicators.`,
  TOUR_DESK_STEP_5: `Display an index or indicator on the map by clicking on its interactive scale.`,
  TOUR_DESK_STEP_6: `To filter school communities in the map based on their resource levels, click within the scale. For example, to show only the “well below average” and “well above average” communities for any given metric, click the darkest blue and darkest green colors at the ends of the scale.`,
  TOUR_MOBILE_STEP_7: `Select this button to display the Map legend.`,
  TOUR_DESK_STEP_7: `The map legend shows which groups of schools are displayed.`,
  TOUR_DESK_STEP_8: `Search for a Dallas ISD neighborhood school here.`,
  TOUR_DESK_STEP_9: `Hover over a school to see a popup showing its main indices. When a school is hovered, its campus community (the area within a 2 mile radius) is highlighted. The index and indicator values describe this area. Click a school dot to open a profile that shows all the data for that campus community.`,
  TOUR_MOBILE_STEP_9: `Select an individual school community to see a popup showing its main indices. When a school is selected, its campus community (the area within a 2 mile radius) is highlighted. The index and indicator values describe this area. A modal dialog displays a profile that shows all the data for that campus community. Use the button in the modal dialog to access a detailed report for the school.`,
  TOUR_MOBILE_STEP_9_1: `When a school is selected, its campus community (the area within a 2 mile radius) is highlighted. The index and indicator values describe this area. A modal dialog displays a profile that shows all the data for that campus community. Use the button in the modal dialog to access a detailed report for the school.`,
  TOUR_MOBILE_STEP_9_2: `Use the button in the modal dialog to access a detailed report for the school.`,
  TOUR_DESK_STEP_10: `Use these controls to zoom in and out, take a screenshot, and reset the map.`,
  TOUR_DESK_STEP_11: `Use the Layers panel to show additional data on the map, like race/ethnicity by census tract.`,
  TOUR_DESK_STEP_12: `The Feeder Pattern view displays all of the feeder patterns in the district. These are sorted according to their average Community Resource Index (CRI), the main index in the Explorer.`,
  TOUR_DESK_STEP_13: `This chart displays all of the neighborhood schools in the district, distributed according to their CRI score.`,
  TOUR_DESK_STEP_14: `Click bars for each feeder to see more information about them.`,
  TOUR_MOBILE_STEP_14: `Click bars for each feeder to see more information about them. When a feeder is selected, a dialog displays more information about the feeder and its schools. Select any school within the dialog to see the profile of the school community in a new tab.`,
  TOUR_DESK_STEP_15: `This panel displays more information about the feeder and its schools. Click any school within the panel to see the profile of the school community in a new tab.`,
  TOUR_DESK_STEP_16: `The distribution chart also highlights all of a feeder's schools when a feeder is selected.`,
  TOUR_DESK_STEP_17: `Search for a school community here and it will be highlighted in the charts.`,
  TOUR_DESK_STEP_18: `The info panel contains insights about each view and how to use the Explorer. If you’d like to take this tour again, you can start here.`,
}

export default en_US
